version: "3.8"

services:
    web:
        image: ${DOCKER_IMAGE}
        container_name: ${PROJECT_NAME}-web
        restart: always
        env_file:
            - .env
        networks:
            - proxy
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=proxy"
            - "traefik.http.routers.${PROJECT_NAME}-secure.entrypoints=websecure"
            - "traefik.http.routers.${PROJECT_NAME}-secure.rule=Host(`${PROJECT_NAME}.${HOST}`)"
            - "traefik.http.services.${PROJECT_NAME}.loadbalancer.server.port=3310"
            - "traefik.http.routers.${PROJECT_NAME}-secure.tls.certresolver=letsencrypt"

networks:
    proxy:
        external: true
