name: CD-Traefik-Deploy

on:
    push:
        branches:
            - staging

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: 📦 Checkout du code
              uses: actions/checkout@v3

            - name: 🔐 Connexion à Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: 🛠️ Build et push de l'image Docker
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ${{ secrets.DOCKER_USERNAME }}/project-${{ vars.PROJECT_NAME }}:latest

            - name: 🚀 Déploiement via SSH (script VPS)
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USER }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  script: |
                      bash ~/traefik/deploy/deploy.sh \
                        "${{ github.repository_owner }}" \
                        "${{ github.event.repository.name }}" \
                        "${{ vars.PROJECT_NAME }}" \
                        "${{ secrets.DOCKER_USERNAME }}"
